# Generated by Django 4.2.2 on 2023-07-05 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_subscriber"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscriber",
            name="email",
        ),
    ]
